export const barsoap = [
  { img: "/barsoap/bravo.png", name: "Bravo Bar" },
  { img: "/barsoap/so-easy.png", name: "So Easy Bar" },
  { img: "/barsoap/mayBar.webp", name: "May Soap 270g" },
  { img: "/barsoap/exoBar.jpg", name: "EXO Bar" },
  { img: "/barsoap/viva.png", name: "Viva Bar" },
  { img: "/barsoap/siri.png", name: "Siri Soap" },
  { img: "/barsoap/DUDU.avif", name: "Dudu OSU" },
  { img: "/barsoap/classy.webp", name: "Classy" },
  { img: "/barsoap/fressia.png", name: "Freesia Cool" },
  { img: "/barsoap/tooclean.jpg", name: "Too Clean Bar" },
  { img: "/barsoap/mamajoy.jpg", name: "Mama Joy 150g" },
  { img: "/barsoap/Mamas-Love.png", name: "Mama's Love" },
  { img: "/barsoap/", name: "Kampe x30" },
  { img: "/barsoap/", name: "Kampe x40" },
  { img: "/barsoap/", name: "Babool x30" },
  { img: "/barsoap/", name: "Babool x60" },
  { img: "/barsoap/mayBar.webp", name: "May Soap 200g" },
  { img: "/barsoap/mayBar.webp", name: "May Cube 350g" },
  { img: "/barsoap/", name: "Palmyra" },
  { img: "/barsoap/", name: "Kampe Cube" },
  { img: "/barsoap/", name: "Mamuda x48" },
  { img: "/barsoap/", name: "Mamuda 300g" },
  { img: "/barsoap/", name: "Home Fresh" },
  { img: "/barsoap/", name: "Daz Bar" },
  { img: "/barsoap/", name: "Soft & Clean" },
  { img: "/barsoap/", name: "Babool Gold" },
  { img: "/barsoap/", name: "Alma Soap" },
  { img: "/barsoap/", name: "Eva Soap" },
  { img: "/barsoap/", name: "Zental" },
  { img: "/barsoap/", name: "Riya Soap" },
  { img: "/barsoap/", name: "Nova Soap" },
];