export const detergent = [
  { img: "/detergent/viva.jpg", name: "Viva 170g" },
  { img: "/detergent/lin.jpg", name: "Klin 170g" },
  { img: "/detergent/soEASY.png", name: "So Easy Premium 90g" },
  { img: "/detergent/goodmama.jpg", name: "Goodmama 170g" },
  { img: "/detergent/wakanda.jpg", name: "Wakanda 170g" },
  { img: "/detergent/kwik.png", name: "Kwik 70g" },
  { img: "/detergent/bravo.avif", name: "Bravo 100g" },
  { img: "/barsoap/mamajoy.jpg", name: "Mama Joy 170g" },
  { img: "/detergent/tooClean.png", name: "Too Clean 170g" },
  { img: "/detergent/sureClean.jpg", name: "Sure Clean 170g" },
  { img: "/detergent/exo.webp", name: "EXO 170g" },
  { img: "/detergent/klinUltra", name: "Klin Ultra 160g" },
  { img: "", name: "Goodmama 800g" },
  { img: "", name: "Bravo 50g" },
  { img: "", name: "Mama Joy 85g" },
  { img: "", name: "Too Clean 85g" },
  { img: "", name: "Viva 80g" },
  { img: "", name: "Viva 800g" },
  { img: "", name: "Klin 80g" },
  { img: "", name: "Klin 800g" },
  { img: "", name: "So Easy Premium 170g" },
  { img: "", name: "So Easy Black 80g" },
  { img: "", name: "So Easy Black 170g" },
  { img: "", name: "Goodmama 80g" },
  { img: "", name: "Wakanda 80g" },
  { img: "", name: "Wakanda 850g" },
  { img: "", name: "Niptol 70g" },
  { img: "", name: "Niptol 170g" },
  { img: "", name: "Niptol 800g" },
  { img: "", name: "Kwik 50g" },
  { img: "", name: "Kwik 800g" },
  { img: "", name: "Supa 140g" },
  { img: "", name: "Supa 800g" },
  { img: "", name: "Sure Clean 80g" },
  { img: "", name: "Visa 165g" },
  { img: "", name: "Visa 75g" },
  { img: "", name: "EXO 70g" },
  { img: "", name: "Polo" },
  { img: "", name: "Nima 170g" },
  { img: "", name: "Nima 80g" },
  { img: "", name: "So Easy Kiddies 160g" },
  { img: "", name: "So Easy Kiddies 75g" },
  { img: "", name: "Klin Smart" },
];